# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u6587\u7ae0\u6807\u9898\uff0c100\u5b57\u4ee5\u5185', max_length=100, verbose_name='\u6807\u9898')),
                ('content', models.TextField(max_length=10000, verbose_name='\u5185\u5bb9')),
                ('floor_num', models.CharField(choices=[('1', '\u4e00\u5c42\u5e73\u623f'), ('2', '\u4e24\u5c42\u522b\u5885'), ('3', '\u4e09\u5c42\u522b\u5885'), ('4', '\u56db\u5c42\u522b\u5885'), ('22', '\u53cc\u62fc\u522b\u5885'), ('0', '\u4e0d\u9650\u5236')], max_length=20, verbose_name='\u522b\u5885\u5c42\u6570')),
                ('floor_area', models.CharField(choices=[('100', '<100\u5e73'), ('200', '100-200\u5e73'), ('300', '200-300\u5e73'), ('400', '\u5927\u4e8e300\u5e73'), ('0', '\u4e0d\u9650\u5236')], max_length=20, verbose_name='\u5360\u5730\u9762\u79ef')),
                ('create_date', models.DateField()),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
