# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
