# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_potho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Potho',
            new_name='Photo',
        ),
    ]
