# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170416_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.CharField(default=0, max_length=10, verbose_name='\u6392\u5e8f\u6807\u5fd7'),
        ),
    ]
