# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170416_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u56fe\u7247\u8bf4\u660e'),
        ),
    ]
