# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 12:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170416_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name='\u6b63\u6587'),
        ),
    ]
