# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170416_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='down_price',
            field=models.IntegerField(default=0, verbose_name='\u4e0b\u8f7d\u79ef\u5206'),
        ),
        migrations.AddField(
            model_name='house',
            name='upload',
            field=models.FileField(blank=True, upload_to='static/uploads'),
        ),
    ]
