# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170430_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='alt',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u56fe\u7247\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u56fe\u7247\u6807\u9898'),
        ),
    ]
